---
services:
  redis:
    image: redis:7
    mem_limit: 1000m
    cpus: 0.5
    ports:
      - 6379:6379/tcp
    restart: always
  ollama:
    image: ollama/ollama:0.3.12
    mem_limit: 4g
    cpus: 4
    ports:
      - 11434:11434/tcp
    volumes:
      - ~/.ollama:/root/.ollama
    restart: always
  tgbot:
    build:
      dockerfile: Dockerfile
    mem_limit: 500m
    cpus: 0.5
    env_file:
      - .env
    environment:
      OLLAMA_HOST: http://olama:11434
      TGBOT_REDIS_ADDR: redis:6379
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
    restart: always
