---
services:
  redis:
    image: redis:7
    mem_limit: 1000m
    cpus: 0.5
    ports:
      - 6379:6379/tcp
    restart: unless-stopped
    volumes:
      - /opt/redis:/data
  ollama:
    image: ollama/ollama:0.3.14
    mem_limit: 40g
    cpus: 8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 11434:11434/tcp
    volumes:
      - /opt/ollama:/root/.ollama
    restart: unless-stopped
  miaou:
    image: mirwide/miaou:v0.1.0
    mem_limit: 500m
    cpus: 0.5
    env_file:
      - .env.local
    environment:
      OLLAMA_HOST: http://ollama:11434
      MIAOU_REDIS_ADDR: redis:6379
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
    restart: unless-stopped
