---
models:
  "gemma2:9b":
    name: gemma2:9b
  "llama3.1:8b":
    name: llama3.1:8b
    tools: true
  "qwen2.5:14b":
    name: qwen2.5:14b
    tools: false
    callback: true
  "llava:13b":
    name: llava:13b
    vision: true
  "llama3.2-vision:11b":
    name: llama3.2-vision:11b
    vision: true
  "t-lite-1.0":
    name: huggingface.co/t-tech/T-lite-it-1.0-Q8_0-GGUF:Q8_0
