// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"es": &dictionary{index: esIndex, data: esData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("ru")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Изображения не поддерживаются в этой версии LLM.": 3,
	"Привет! Расскажи кратко, что ты умеешь.":          4,
	"Произошла ошибка, попробуйте позже.":              0,
	"Размер ответа сокращён до 4096 символов.":         5,
	"Слишком много запросов, попробуйте позже.":        2,
	"Текущая модель: %s.":                              1,
	"Текущая модель: %s. Выберите другую:":             6,
}

var enIndex = []uint32{ // 8 elements
	0x00000000, 0x0000002b, 0x00000047, 0x00000072,
	0x000000a3, 0x000000cb, 0x00000102, 0x0000012e,
} // Size: 56 bytes

const enData string = "" + // Size: 302 bytes
	"\x02An error occurred, please try again later.\x02The current model is %" +
	"[1]s.\x02Too many requests, please try again later.\x02Images are not su" +
	"pported in this version of LLM.\x02Hello! Tell me briefly what you can d" +
	"o.\x02The response size has been reduced to 4096 characters.\x02The curr" +
	"ent model is %[1]s. Select another:"

var esIndex = []uint32{ // 8 elements
	0x00000000, 0x0000002a, 0x00000045, 0x00000074,
	0x000000ae, 0x000000de, 0x0000011b, 0x00000147,
} // Size: 56 bytes

const esData string = "" + // Size: 327 bytes
	"\x02Ocurrió un error, inténtalo más tarde.\x02El modelo actual es %[1]s." +
	"\x02Demasiadas solicitudes, inténtalo más tarde.\x02Las imágenes no son " +
	"compatibles en esta versión de LLM.\x02¡Hola! Cuéntame brevemente qué pu" +
	"edes hacer.\x02El tamaño de la respuesta se ha reducido a 4096 caractere" +
	"s.\x02El modelo actual es %[1]s. Selecciona otro:"

var ruIndex = []uint32{ // 8 elements
	0x00000000, 0x00000042, 0x00000066, 0x000000b3,
	0x0000010a, 0x00000151, 0x00000198, 0x000001db,
} // Size: 56 bytes

const ruData string = "" + // Size: 475 bytes
	"\x02Произошла ошибка, попробуйте позже.\x02Текущая модель: %[1]s.\x02Сли" +
	"шком много запросов, попробуйте позже.\x02Изображения не поддерживаются" +
	" в этой версии LLM.\x02Привет! Расскажи кратко, что ты умеешь.\x02Размер" +
	" ответа сокращён до 4096 символов.\x02Текущая модель: %[1]s. Выберите др" +
	"угую:"

	// Total table size 1272 bytes (1KiB); checksum: C39ABF0A
