// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("ru-RU")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Запрос принят.": 0,
}

var en_USIndex = []uint32{ // 2 elements
	0x00000000, 0x00000012,
} // Size: 32 bytes

const en_USData string = "\x02Request accepted."

var ru_RUIndex = []uint32{ // 2 elements
	0x00000000, 0x0000001b,
} // Size: 32 bytes

const ru_RUData string = "\x02Запрос принят."

// Total table size 109 bytes (0KiB); checksum: A57ACF49
